### ISSUE TITLE
PIDS: create endpoint to "reserve DOI"

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-records-resources#224]
Create a new REST APIs endpoint to be able to perform an action on a configured managed PID provider.
For the time being, the simplest use case is the DOI reservation.

## Tasks

- [ ] define the endpoint URL, verb and needed params.
- [ ] create a new view in the resources module
- [ ] define permissions: probable any authenticated user?
- [ ] return a response with the reserved DOI

As first implementation, simply return a random string. In a second step, the new resource should use a service to reserve and obtain a DOI.
